"""gateway_foundations

Revision ID: 0001
Revises:
Create Date: 2026-07-11 20:50:39.354601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_users_api_key'), 'admin_users', ['api_key'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('owner_department', sa.String(length=128), nullable=True),
    sa.Column('owner_user', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('supported_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_key'), 'agents', ['agent_key'], unique=True)
    op.create_index(op.f('ix_agents_api_key'), 'agents', ['api_key'], unique=True)
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=False)
    op.create_table('approval_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_key', sa.String(length=128), nullable=False),
    sa.Column('ticket_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('applicant', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_tickets_ticket_key'), 'approval_tickets', ['ticket_key'], unique=True)
    op.create_table('asset_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_key', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_candidates_asset_type'), 'asset_candidates', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_candidates_candidate_key'), 'asset_candidates', ['candidate_key'], unique=True)
    op.create_index(op.f('ix_asset_candidates_status'), 'asset_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_asset_candidates_submitted_by'), 'asset_candidates', ['submitted_by'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('resource_version', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('input_digest', sa.String(length=128), nullable=True),
    sa.Column('output_digest', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_task_id'), 'audit_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('scenarios', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_level', sa.String(length=64), nullable=False),
    sa.Column('owner_department', sa.String(length=128), nullable=True),
    sa.Column('owner_user', sa.String(length=128), nullable=True),
    sa.Column('allowed_agent_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('side_effect', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_business_domain'), 'capabilities', ['business_domain'], unique=False)
    op.create_index(op.f('ix_capabilities_capability_key'), 'capabilities', ['capability_key'], unique=True)
    op.create_index(op.f('ix_capabilities_status'), 'capabilities', ['status'], unique=False)
    op.create_index(op.f('ix_capabilities_type'), 'capabilities', ['type'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('owner_department', sa.String(length=128), nullable=True),
    sa.Column('security_level', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieval_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_kb_key'), 'knowledge_bases', ['kb_key'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_policy_key'), 'policies', ['policy_key'], unique=True)
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_prompt_key'), 'prompt_templates', ['prompt_key'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('business_domain', sa.String(length=128), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependencies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_agent_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('prompt_key', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_skill_key'), 'skills', ['skill_key'], unique=True)
    op.create_table('capability_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_code', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability_id', 'subject_type', 'subject_code', 'permission', name='uq_capability_permission_subject')
    )
    op.create_index(op.f('ix_capability_permissions_capability_id'), 'capability_permissions', ['capability_id'], unique=False)
    op.create_index(op.f('ix_capability_permissions_permission'), 'capability_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_capability_permissions_status'), 'capability_permissions', ['status'], unique=False)
    op.create_index(op.f('ix_capability_permissions_subject_code'), 'capability_permissions', ['subject_code'], unique=False)
    op.create_index(op.f('ix_capability_permissions_subject_type'), 'capability_permissions', ['subject_type'], unique=False)
    op.create_table('capability_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability_id', 'version', name='uq_capability_version')
    )
    op.create_table('collaboration_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_key', sa.String(length=128), nullable=False),
    sa.Column('caller_agent_id', sa.UUID(), nullable=True),
    sa.Column('caller_agent_key', sa.String(length=128), nullable=False),
    sa.Column('task_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtask_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caller_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_tasks_caller_agent_key'), 'collaboration_tasks', ['caller_agent_key'], unique=False)
    op.create_index(op.f('ix_collaboration_tasks_status'), 'collaboration_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_collaboration_tasks_task_key'), 'collaboration_tasks', ['task_key'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('object_uri', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('security_level', sa.String(length=64), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('title_path', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('security_level', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_table('documents')
    op.drop_index(op.f('ix_collaboration_tasks_task_key'), table_name='collaboration_tasks')
    op.drop_index(op.f('ix_collaboration_tasks_status'), table_name='collaboration_tasks')
    op.drop_index(op.f('ix_collaboration_tasks_caller_agent_key'), table_name='collaboration_tasks')
    op.drop_table('collaboration_tasks')
    op.drop_table('capability_versions')
    op.drop_index(op.f('ix_capability_permissions_subject_type'), table_name='capability_permissions')
    op.drop_index(op.f('ix_capability_permissions_subject_code'), table_name='capability_permissions')
    op.drop_index(op.f('ix_capability_permissions_status'), table_name='capability_permissions')
    op.drop_index(op.f('ix_capability_permissions_permission'), table_name='capability_permissions')
    op.drop_index(op.f('ix_capability_permissions_capability_id'), table_name='capability_permissions')
    op.drop_table('capability_permissions')
    op.drop_index(op.f('ix_skills_skill_key'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_prompt_templates_prompt_key'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_policies_policy_key'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_knowledge_bases_kb_key'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_capabilities_type'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_status'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_key'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_business_domain'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_task_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asset_candidates_submitted_by'), table_name='asset_candidates')
    op.drop_index(op.f('ix_asset_candidates_status'), table_name='asset_candidates')
    op.drop_index(op.f('ix_asset_candidates_candidate_key'), table_name='asset_candidates')
    op.drop_index(op.f('ix_asset_candidates_asset_type'), table_name='asset_candidates')
    op.drop_table('asset_candidates')
    op.drop_index(op.f('ix_approval_tickets_ticket_key'), table_name='approval_tickets')
    op.drop_table('approval_tickets')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_index(op.f('ix_agents_api_key'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_key'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_admin_users_api_key'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
